### PR TITLE
Delete qUINT_bloom.fx

### PR DESCRIPTION
**Pull request by LaRty007**

### CODE REVIEW

**Comment by NekoAlosama** [comment]
Explain.

**Comment by NekoAlosama** [comment]
@martymcmodding Likely troll account. Made just a few minutes ago.
Screenshot 2021-11-06 19 24 38
.

**Comment by NekoAlosama** [comment]
Empty repo with keyboard-smash name.
Screenshot 2021-11-06 19 54 51

**Comment by NekoAlosama** [comment]
I noticed another person in some repos I follow with some similarities to this one: 
https://github.com/Rafo660
Some differences though, like having a few more PRs, only adding files, and saying "Ок" (which uses Russian letters). I'm looking over these types of accounts.

**Comment by NekoAlosama** [comment]
Rafo660's account has been removed, and I don't know if this person would do much more.

**Comment by martymcmodding** [comment]
I don't even know what that's supposed to accomplish. For github, it just creates a miniscule amount of wasted data, for me it's a single click and a chuckle to deny, and even if I misclicked, I could revert the PR with one click as well. Some people really spend their time ineffectively.

**Pull request closed without merging**
